name: Master Orchestrator Pipeline

on:
  push:
    branches:
      - main              # Trigger when code is pushed to main
  workflow_dispatch:      # Allow manual trigger from GitHub UI
  schedule:
    - cron: "0 9 * * *"   # Optional: Daily at 9 AM UTC (2 PM PKT)

permissions:
  contents: write
  id-token: write

jobs:
  # Step 1: Run fetch + feature eng + selection in parallel
  trigger-parallel-jobs:
    name: Run Fetch + Feature Engineering + Selection
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily AQI & Weather Data Fetch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Daily AQI & Weather Data Fetch
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Trigger Feature Engineering
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Feature Engineering
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Trigger Feature Selection
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Feature Selection
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  # Step 2: Wait before triggering AQI Prediction
  wait-for-previous:
    name: Wait for Upstream Jobs
    needs: trigger-parallel-jobs
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 2 minutes
        run: sleep 120

  # Step 3: Trigger AQI Prediction
  trigger-aqi-prediction:
    name: Run AQI Prediction
    needs: wait-for-previous
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AQI Prediction
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: AQI Prediction
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  # Step 4: Wait again
  wait-for-prediction:
    name: Wait for Prediction to Finish
    needs: trigger-aqi-prediction
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 2 minutes
        run: sleep 120

  # Step 5: Trigger BentoML AQI Forecast
  trigger-bentoml:
    name: Run BentoML Forecast
    needs: wait-for-prediction
    runs-on: ubuntu-latest
    steps:
      - name: Trigger BentoML AQI Forecast
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: BentoML AQI Forecast
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
