name: AQI Prediction

on:
  schedule:
    - cron: "0 12 * * *"  # Every day at 5 PM PKT
  workflow_dispatch:         # Allows manual run from GitHub

jobs:
  aqi-prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn statsmodels dvc[s3] bentoml==1.2.0

      - name: Pull feature_selection.csv from S3 (via DVC)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: dvc pull

      - name: Run AQI prediction script
        run: python "Model Training/predict_next_3days.py"

      - name: Track predictions.csv with DVC
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: dvc add predictions.csv

      - name: Commit predictions.csv.dvc to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add predictions.csv.dvc .gitignore
          git commit -m "Update predictions.csv via DVC [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: ☁️ Push predictions data to S3 (via DVC)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: dvc push

      - name: 🔍 Get latest SARIMAX BentoML model tag
        id: get_model_tag
        run: |
          MODEL_TAG=$(ls ~/.bentoml/models/sarimax_model | sort | tail -n 1)
          echo "MODEL_TAG=$MODEL_TAG" >> $GITHUB_ENV

      - name: 📦 Export SARIMAX model to .bentoml archive
        run: |
          bentoml models export "sarimax_model:$MODEL_TAG" "sarimax_model_$MODEL_TAG.bentoml"

      - name: ☁️ Upload SARIMAX model to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 cp "sarimax_model_$MODEL_TAG.bentoml" "s3://s3-bucket-umairrr/models/"
